CREATE TABLE roles(
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE users(
 id BIGSERIAL PRIMARY KEY,
 username VARCHAR(100) UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 enabled BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles(
 user_id BIGINT REFERENCES users(id),
 role_id BIGINT REFERENCES roles(id),
 PRIMARY KEY(user_id, role_id)
);

INSERT INTO roles(name) VALUES
('SUPER_ADMIN'),
('HR_DIRECTOR'),
('REGISTRAR'),
('LECTURER');
