import { useEffect, useState } from 'react';
import {
  Alert,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  MenuItem,
  Stack,
  TextField,
} from '@mui/material';
import { httpClient } from '../../app/httpClient';
import type { AssignableHead, OrgUnit, OrgUnitType, SubmitChangeRequestPayload } from './types';

export type ProposeMode = 'create-root' | 'create-child' | 'update' | 'archive';

interface ProposeChangeDialogProps {
  open: boolean;
  mode: ProposeMode;
  parentUnit?: OrgUnit;
  targetUnit?: OrgUnit;
  onClose: () => void;
  onSubmitted: () => void;
}

const CHILD_TYPE_FOR: Record<OrgUnitType, OrgUnitType> = {
  COLLEGE: 'FACULTY',
  FACULTY: 'DEPARTMENT',
  DEPARTMENT: 'UNIT',
  UNIT: 'UNIT',
};

function childTypeFor(parentType: OrgUnitType): OrgUnitType {
  return CHILD_TYPE_FOR[parentType];
}

const AUTO_CODE_TYPES: OrgUnitType[] = ['COLLEGE', 'FACULTY'];

export function ProposeChangeDialog({ open, mode, parentUnit, targetUnit, onClose, onSubmitted }: ProposeChangeDialogProps) {
  const [name, setName] = useState('');
  const [code, setCode] = useState('');
  const [headId, setHeadId] = useState<string>('');
  const [heads, setHeads] = useState<AssignableHead[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!open) return;
    setError(null);
    setName(mode === 'update' && targetUnit ? targetUnit.name : '');
    setCode(mode === 'update' && targetUnit ? targetUnit.code : '');
    setHeadId(mode === 'update' && targetUnit?.headId ? String(targetUnit.headId) : '');

    if (mode !== 'archive') {
      httpClient
        .get<AssignableHead[]>('/api/org/units/assignable-heads')
        .then((res) => setHeads(res.data))
        .catch(() => setHeads([]));
    }
  }, [open, mode, targetUnit]);

  const isCreate = mode === 'create-root' || mode === 'create-child';
  const title = isCreate ? 'Propose new org unit' : mode === 'update' ? 'Propose edit' : 'Propose archive';
  const typeToCreate: OrgUnitType | null =
    mode === 'create-root' ? 'COLLEGE' : mode === 'create-child' && parentUnit ? childTypeFor(parentUnit.type) : null;
  const hasAutoGeneratedCode = typeToCreate !== null && AUTO_CODE_TYPES.includes(typeToCreate);

  async function handleSubmit() {
    setError(null);
    setSubmitting(true);
    try {
      const payload: SubmitChangeRequestPayload =
        mode === 'archive'
          ? { action: 'ARCHIVE', targetOrgUnitId: targetUnit!.id }
          : mode === 'update'
            ? {
                action: 'UPDATE',
                targetOrgUnitId: targetUnit!.id,
                proposedName: name,
                proposedCode: code,
                ...(headId ? { proposedHeadId: Number(headId) } : {}),
              }
            : {
                action: 'CREATE',
                proposedName: name,
                proposedType: typeToCreate!,
                ...(hasAutoGeneratedCode ? {} : { proposedCode: code }),
                ...(mode === 'create-child' && parentUnit ? { proposedParentId: parentUnit.id } : {}),
                ...(headId ? { proposedHeadId: Number(headId) } : {}),
              };

      await httpClient.post('/api/org/change-requests', payload);
      onSubmitted();
      onClose();
    } catch (err: unknown) {
      const message =
        (err as { response?: { data?: { message?: string } } })?.response?.data?.message ??
        'Could not submit this request.';
      setError(message);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>{title}</DialogTitle>
      <DialogContent>
        {error && (
          <Alert severity="error" sx={{ mb: 2 }}>
            {error}
          </Alert>
        )}

        {mode === 'archive' ? (
          <DialogContentText>
            Propose archiving <strong>{targetUnit?.name}</strong>? This requires SYSTEM_ADMIN approval and will be
            rejected if the unit still has active children.
          </DialogContentText>
        ) : (
          <Stack spacing={2} sx={{ mt: 1 }}>
            {mode === 'create-child' && parentUnit && (
              <DialogContentText>
                Adding a {childTypeFor(parentUnit.type)} under <strong>{parentUnit.name}</strong>.
              </DialogContentText>
            )}
            <TextField label="Name" value={name} onChange={(e) => setName(e.target.value)} required fullWidth />
            {hasAutoGeneratedCode ? (
              <DialogContentText variant="body2">
                A {typeToCreate === 'COLLEGE' ? 'college' : 'faculty'} code will be generated automatically from the
                name.
              </DialogContentText>
            ) : (
              <TextField label="Code" value={code} onChange={(e) => setCode(e.target.value)} required fullWidth />
            )}
            <TextField
              select
              label="Head (optional)"
              value={headId}
              onChange={(e) => setHeadId(e.target.value)}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {heads.map((h) => (
                <MenuItem key={h.id} value={String(h.id)}>
                  {h.firstName} {h.lastName} ({h.username})
                </MenuItem>
              ))}
            </TextField>
          </Stack>
        )}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={submitting}>
          Cancel
        </Button>
        <Button onClick={handleSubmit} variant="contained" disabled={submitting}>
          {submitting ? 'Submitting…' : 'Submit for approval'}
        </Button>
      </DialogActions>
    </Dialog>
  );
}
