spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniservice
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
logging:
  level:
    root: INFO
